name: Run Chartink AI

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
  
on:
  schedule:
  - cron: '0 9 * * *'    # 14:30 IST
  - cron: '30 15 * * *'  # 21:00 IST
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          playwright install --with-deps

      - name: Run script
        run: python test.py
